accounts/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    path("signup", SignUpView.as_view(), name="signup"),
]

budget/urls.py
from django.urls import path
from .views import (
    AccountListView,
    AccountDetailView,
    AccountCreateView,
    AccountUpdateView,
    AccountDeleteView,
    TransactionCreateView,
    TransactionUpdateView,
    TransactionDeleteView,
)

urlpatterns = [
    path("", AccountListView.as_view(), name="home"),
    path("account/<int:pk>/", AccountDetailView.as_view(), name="account_detail"),
    path("account/new/", AccountCreateView.as_view(), name="account_new"),
    path("account/<int:pk>/edit/", AccountUpdateView.as_view(), name="account_edit"),
    path(
        "account/<int:pk>/delete/", AccountDeleteView.as_view(), name="account_delete"
    ),
    path("transaction/new/", TransactionCreateView.as_view(), name="transaction_new"),
    path(
        "transaction/<int:pk>/edit/",
        TransactionUpdateView.as_view(),
        name="transaction_edit",
    ),
    path(
        "transaction/<int:pk>/delete/",
        TransactionDeleteView.as_view(),
        name="transaction_delete",
    ),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts", include("accounts.urls")),
    path("", include("budget.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

budget/models.py
from django.db import models
from django.utils.timezone import now
from django.urls import reverse


# Modify later to include currency type in Account model
#   can be used for display purposes in views
class Account(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def get_balance(self):
        sum = 0
        for transaction in self.transaction_set.all():
            sum += transaction.amount
        return sum

    def get_absolute_url(self):
        return reverse("account_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.user} {self.name}"


# leaving Categories out for now, not sure how I want to implement the form for this yet

# class Category(models.Model):
#     name = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.name


class Transaction(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=18, decimal_places=2)
    date = models.DateField(default=now)

    # category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def get_current_balance(self):
        sum = self.amount

        older_transactions = Transaction.objects.filter(
            id__lt=self.id, account=self.account
        )
        for transaction in older_transactions:
            sum += transaction.amount
        return sum

    def __str__(self):
        return f"{self.date}: {self.amount}"


# class RecurringTransaction(models.Model):
#     account = models.ForeignKey(Account, on_delete=models.CASCADE)
#     amount = models.DecimalField(max_digits=18, decimal_places=2)
#     category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
#     date = models.DateField(default=now)

#     def __str__(self):
#         return f"{self.date}: {self.amount}"

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.shortcuts import render


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

budget/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.urls import reverse, reverse_lazy

from .models import Account, Transaction


class AccountListView(ListView):
    model = Account
    template_name = "home.html"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Account.objects.filter(user=self.request.user)


class AccountDetailView(DetailView):
    model = Account
    template_name = "account_detail.html"

    def get_queryset(self):
        return Account.objects.filter(user=self.request.user)


class AccountCreateView(CreateView):
    model = Account
    template_name = "account_new.html"
    fields = ["name"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AccountUpdateView(UpdateView):
    model = Account
    template_name = "account_edit.html"
    fields = ["name"]

    def get_queryset(self):
        return Account.objects.filter(user=self.request.user)


class AccountDeleteView(DeleteView):
    model = Account
    template_name = "account_delete.html"
    success_url = reverse_lazy("home")

    def get_queryset(self):
        return Account.objects.filter(user=self.request.user)


class TransactionCreateView(CreateView):
    model = Transaction
    template_name = "transaction_new.html"
    fields = ["account", "amount", "date"]

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["account"].queryset = Account.objects.filter(user=self.request.user)
        return form

    def get_success_url(self):
        return reverse("account_detail", kwargs={"pk": self.object.account.pk})


class TransactionUpdateView(UpdateView):
    model = Transaction
    template_name = "transaction_edit.html"
    fields = ["amount", "date"]

    def get_success_url(self):
        return reverse("account_detail", kwargs={"pk": self.object.account.pk})


class TransactionDeleteView(DeleteView):
    model = Transaction
    template_name = "transaction_delete.html"
    success_url = reverse_lazy("home")

templates/account_delete.html
{% extends "base.html" %}

{% block content %}

<h2>Delete Account</h2>
<form action="" method="post">
  {% csrf_token %}

  <p>Are you sure you want to delete the account {{ account.name }}?</p>

  <input type="submit" value="Confirm">
</form>

{% endblock %}

templates/account_detail.html
{% extends "base.html" %}

{% block content %}

  <h2>{{ account.name }}</h2>
  <h3>£{{ account.get_balance }}</h3>

  <a href="{% url 'account_edit' account.pk %}">Edit</a>
  <a href="{% url 'account_delete' account.pk %}">Delete</a>

  {% for transaction in account.transaction_set.all %}
    <p>{{ transaction.date }}: £{{ transaction.amount }}, Account Balance: £{{ transaction.get_current_balance }} <a href="{% url 'transaction_edit' transaction.pk %}">Edit</a> <a href="{% url 'transaction_delete' transaction.pk %}">Delete</a></p>
  {% empty %}
    <p>No transactions found for this account.</p>
  {% endfor %}

{% endblock %}

templates/account_edit.html
{% extends "base.html" %}

{% block content %}
  <h2>Edit Account</h2>
  <form action="" method="post">
    {% csrf_token %}

    {{ form }}

    <input type="submit" value="Update">
  
  </form>

{% endblock %}

templates/account_new.html
{% extends "base.html" %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save">
  </form>

{% endblock %}

templates/base.html
<html>
  <head>
    <title>Budget App</title>
  </head>

  <body>
    <a href="{% url 'home' %}"><h1>Budget App</h1></a>


    {% if user.is_authenticated %}
      <p> Hi {{ user.username }} </p>
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Log Out</button>
      </form>
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
      <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
    
    <div>
      
      {% block content %}
      {% endblock content %}
    
    </div>

  </body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

  {% if user.is_authenticated %}
    <p><a href="{% url 'account_new' %}">Create New Account</a></p>
    <p><a href="{% url 'transaction_new' %}">New Transaction</a></p>

    <h2>All Accounts</h2>

    {% for account in account_list %}
      <div>
        <a href="{{ account.get_absolute_url }}"><h3>{{ account.name }}</h3></a>
        <p>£{{ account.get_balance }}</p>
        <p>{{ account.user }}</p>
      </div>
    {% endfor %}

  {% else %}

    <p>Please login to view your accounts</p>
  
  {% endif %}

{% endblock content %}

templates/transaction_delete.html
{% extends "base.html" %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}

    <p>{{ transaction.date }} {{ transaction.amount }}</p>

    <p>Are you sure you want to delete this transaction?</p>

    <input type="submit" valu="Confirm">
  </form>

{% endblock %}

templates/transaction_edit.html
{% extends "base.html" %}

{% block content %}

  <form action="" method="post">
    
    {% csrf_token %}
    
    {{ form }}
  
    <input type="submit" value="Update">  

  </form>

{% endblock %}

templates/transaction_new.html
{% extends "base.html" %}

{% block content %}

  <form action="" method="post">
    {% csrf_token %}

    {{ form }}

    <input type="submit" value="Save">

  </form>

{% endblock %}